services:
  - type: web
    name: dinnerduty
    runtime: node
    plan: free
    region: frankfurt  
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_MODE
        value: basic
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_EMAILS
        value: bsksi@aarhus.dk
      - key: ADMIN_PASSWORD
        value: Annerboss!
    disk:
      name: data-disk
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    healthCheckPath: /